name: Deploy to Develop

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ejecutar script en EC2 con SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets '[{"Key":"instanceIds","Values":["i-029ce131c546e1690"]}]' \
            --parameters 'commands=["bash stop_server.sh"]' \
            --region us-east-1 \
            --output text
